### ISSUE TITLE
select visually and send to repl

### ISSUE THREAD

**Issue by Yousuf28** [milanglacier/yarepl.nvim#11]
Thanks for amazing plugin. 
I am using vim-slime now for running R code. In any line I can hit C-c C-c to send to terminal. Also I can visually select and hit same keybinding to send block of code to R console. 
How can I do the same thing in yarepl?
vim.api.nvim_set_keymap("n", "<C-Enter>", ":REPLSendLine <CR>", {silent = true}) in init.lua works to send line. 
How can I select line visually and run? Is there any easy mapping?

Thanks

**Comment by milanglacier** [comment]
Yes, you can. you can check for [Example keybinding setup](https://github.com/milanglacier/yarepl.nvim#example-keybinding-setup) section at the README.

Some notable lines include:

```lua
local function run_cmd_with_count(cmd)
    return function()
        vim.cmd(string.format('%d%s', vim.v.count, cmd))
    end
end

local ft_to_repl = {
    r = 'radian',
    rmd = 'radian',
    quarto = 'radian',
    markdown = 'radian',
    ['markdown.pandoc'] = 'radian',
    python = 'ipython',
    sh = 'bash',
    REPL = '',
}

local keymap = vim.api.nvim_set_keymap
local bufmap = vim.api.nvim_buf_set_keymap
local autocmd = vim.apip.nvim_create_auto_autocmd

autocmd('FileType', {
    pattern = { 'quarto', 'markdown', 'markdown.pandoc', 'rmd', 'python', 'sh', 'REPL' },
    desc = 'set up REPL keymap',
    callback = function()
        bufmap(0, 'v', '<LocalLeader>s', '', {
            callback = run_cmd_with_count 'REPLSendVisual',
            desc = 'Send visual region to REPL',
        })
        bufmap(0, 'n', '<LocalLeader>ss', '', {
            callback = run_cmd_with_count 'REPLSendLine',
            desc = 'Send current line to REPL',
        })
        -- `<LocalLeader>sap` will send the current paragraph to the
        -- buffer-attached REPL, or REPL 1 if there is no REPL attached.
        -- `2<Leader>sap` will send the paragraph to REPL 2. Note that `ap` is
        -- just an example and can be replaced with any text object or motion.
        bufmap(0, 'n', '<LocalLeader>s', '', {
            callback = run_cmd_with_count 'REPLSendMotion',
            desc = 'Send motion to REPL',
        })
end
```
 
`yarepl` supports multiple paradigms to interact with REPLs, that is why I haven't create any default keybindings. Because I want user to create their own keybindings based on how they like to interact with REPLs.

In my example keybinding setup, there are three keymaps for sending code to REPL. The first two are `<localleader>s` (either send visual lines or acting as an operator to send motion/text objects to the REPL), and `<localleader>ss` is to send current line to REPL.

When `<localleader>s` is acted as an operator, it is also dot repeatable. That is, suppose you have used `<localledaer>sap` to send a paragraph to the REPL, all you need to is to press `.` to repeat this behavior).

I will explain my keybinding setup a bit more in detail:

If you are currently on a R file, then `<LocalLeader>rs` will start a `radian` repl with id 1, and `2<LocalLeader>rs`will start a `radian` REPL with id 2, etc.

And `<LocalLeader>s`, `<Localleader>ss` will send code to REPL with id 1 and `2<LocalLeader>ss`, `2<LocalLeader>s` will send code to the second REPL. This gives me availability to send code within from any files to any REPLs.

In case I don't want to remember the specific REPL id everytime I want to send code a specific REPL, I will use `<LocalLeader>ra` which will attach current buffer to an existing REPL. And after that, I will simply call `<localleader>s`, `<Localleadder>ss` etc. without any numeric prefix, and I can make sure that all the code within current file will be sent to the desired REPL.

Hope my example keybinding setup can help you!

**Comment by Yousuf28** [comment]
Thank you for details explanation. Everything working except visual selection (I got work around). I don't know what I am doing wrong.
My localleader is coma `,`. when I hit `,s` it only show sendline and motion key on which-key pop up. even though I set sendvisual as `,sv`. It does not show up here. When I visually select and hit `,s` cursor goes into insert mode. 

![SharedScreenshot](https://github.com/milanglacier/yarepl.nvim/assets/31291716/f0b31706-d490-45cf-aa48-3e90a1e2ef4f)

- [Here is my init.lua file](https://github.com/Yousuf28/kickstart.nvim/blob/windows/init.lua#L886)

but things get interesting. If I put this line in init.lua file, 
```
map('v', "<LocalLeader>sk", ":REPLSendVisual <CR>")
 
```
 then `,sv` works after visual selection. 
but `,sk` does give me error E16: Invalid Range.

[map function here](https://github.com/Yousuf28/kickstart.nvim/blob/windows/lua/utils.lua#L5)
after further testing, it seems 
```
map('v', "<LocalLeader>sk", ":noh <CR>")
```
even if I put above line, still `,sv` works. 
It seems to me  that a keymap for  `'v'` visual mode need to put somewhere for `,sv` to works

**Comment by Yousuf28** [comment]
update: 
If I don't use localleader or leader, visual selction work fine with control+enter like following keymap
```
autocmd('FileType', {
    pattern = { 'quarto', 'r', 'markdown', 'markdown.pandoc', 'rmd', 'python', 'sh', 'REPL' },
    desc = 'set up REPL keymap',
    callback = function()
        bufmap(0, 'v', '<C-Enter>', '', {
            callback = run_cmd_with_count 'REPLSendVisual',
            desc = 'Send visual region to REPL',
        })
        bufmap(0, 'n', '<C-Enter>', '', {
            callback = run_cmd_with_count 'REPLSendLine',
            desc = 'Send current line to REPL',
        })
        -- `<LocalLeader>sap` will send the current paragraph to the
        -- buffer-attached REPL, or REPL 1 if there is no REPL attached.
        -- `2<Leader>sap` will send the paragraph to REPL 2. Note that `ap` is
        -- just an example and can be replaced with any text object or motion.
        bufmap(0, 'n', '<LocalLeader>sm', '', {
            callback = run_cmd_with_count 'REPLSendMotion',
            desc = 'Send motion to REPL',
        })
end,
})
```

**Comment by milanglacier** [comment]
when using a visual keymap, you should either use `:<C-U>xxxxx<CR>` or `<CMD>xxxxxx<CR>`, where `xxx` is the command you are using. The `<C-U>` quirk is almost everywhere when you want to map a command to a keymap in visual mode.

If you are intersted in the reason why there's a weird `<C-U>` in the keymap. Because `REPLSendVisual` does not accept ranges as parameters and when you visually selected ranges, the ranges are activated and you must use `<C-U>` to clear them.

And you don't need `<C-U>` when using `<CMD>` is because that `REPLSendVisual` will internally clear the visual range, but only when you are using `vim.cmd` or `<CMD>` which does not act like a keyboard macro. `:REPLSendVisual` acts like a macro and that is the reason you must use `<C-U>`.
