### ISSUE TITLE
newbie question: sending strings/commands from script?

### ISSUE THREAD

**Issue by gilbh** [milanglacier/yarepl.nvim#13]
How can I send a set of commands from a script? Something like:
```
REPL %run 'filename.py'
```

?

**Comment by milanglacier** [comment]
What do you mean by this?

You want to send the following line:

```
%run 'filename.py'
```

to the REPL?

**Comment by gilbh** [comment]
yes, and also other commands like `%pdb` and, if inside ipdb/breakpoint, `args` `next` `until` etc.

**Comment by milanglacier** [comment]
I understand what you mean.

currently you can write write those commands in your script and use `REPLSendLine` to send them to the line to the REPL.

but I do agree that it is less convenient to write the commands in the file and send them to the REPL because you will need to delete those lines later.

I will add a new neovim command that allows the user to send the string typed in the cmd line to the REPL (based on which of course you can create the keymappings easily later)

But I need some time to think about the command name and the API design. (Any suggestions on the design is welcomed!)

If you are interested in, you can also write your own function using the internal function `Yarepl._send_strings` which allows you to send arbitrary strings to a designated REPL.

**Comment by gilbh** [comment]
Thanks. 

Yes, it needs some design. 

One difficult subject is sending multilines, motions, and commands from script.

In vimscript, I ended up writing a function that uses `nvim_feedkeys` and makes sure to send specials characters. It's very clunky but works on Windows. 

Start at the bottom with `call Start_ipython()`. 
```
function! SSKT(keys_to_term)  " S/end S/pecial K/eys to T/erminal
  " for sending special characters to terminal buffer
  let key = nvim_replace_termcodes(a:keys_to_term, v:true, v:false, v:true)
  call nvim_feedkeys(key, 'n', v:false)
endfunction
function! Windows_Terminal_Command(command_to_term, shell_level)
  let return_to_left_window_when_done = 0
  if expand('%')[0:6] == 'term://'
    if mode() == 'n'
      call nvim_feedkeys('i', 'n', v:false)
    endif
  else
    let return_to_left_window_when_done = 1
    call SSKT('<C-w>l')
    call nvim_feedkeys('i', 'n', v:false)
  endif
  call nvim_feedkeys(a:command_to_term, 'n', v:false)
  if a:shell_level == 0  " Windows Command Line level
    call SSKT('<cr>')
  elseif a:shell_level == 1  " ipyhton level
    call SSKT('<nl>')
  endif
  call SSKT('<C-\><C-n>')
  if return_to_left_window_when_done
    call SSKT('<C-w>h')
  else
    call nvim_feedkeys('i', 'n', v:false)
  endif
endfunction
function! Windows_Terminal_Command_ipython(command_to_term)
  call Windows_Terminal_Command(a:command_to_term, 1)
endfunction
function! Windows_Terminal_Command_CMD(command_to_term)
  call Windows_Terminal_Command(a:command_to_term, 0)
endfunction
function! Start_ipython()
  call Windows_Terminal_Command_CMD('ipython')
  call Windows_Terminal_Command_ipython('%pdb on')
endfunction

call Start_ipython()
```

The gist is that there are two separate ways to enter newline whether in Windows command line or inside ipython:
```
  if a:shell_level == 0  " Windows Command Line level
    call SSKT('<cr>')
  elseif a:shell_level == 1  " ipyhton level
    call SSKT('<nl>')
  endif
```

**Comment by milanglacier** [comment]
It will not be that cumbersome in lua because we will use the  `chansend` function which will handles some of the annoying shell escape for us.

And lua is also not as awful as vimscript.

And we will only interact within neovim, the terminal emulator will be irrelevant.

but there are still some questions remained to be designed, for example in neovim cmd line, `%` can be used for interpolation (can be interpolated as the file name of current buffer).

How do we handle `%` appeared in the cmd line, how do we handle multiple line input in cmd line? These will be questions remained to solved.

Sending motions and multi-lines in scripts is not relevant here, we already have `REPLSendVisual` and `REPLSendMotion` for sending text from buffer directly.

**Comment by gilbh** [comment]
> It will not be that cumbersome in lua because we will use the `chansend` function which will handles some of the annoying shell escape for us.
> 
> And lua is also not as awful as vimscript.
> 
> And we will only interact within neovim, the terminal emulator will be irrelevant.
> 
> but there are still some questions remained to be designed, for example in neovim cmd line, `%` can be used for interpolation (can be interpolated as the file name of current buffer).
> 
> How do we handle `%` appeared in the cmd line, how do we handle multiple line input in cmd line? These will be questions remained to solved.
> 
> Sending motions and multi-lines in scripts is not relevant here, we already have `REPLSendVisual` and `REPLSendMotion` for sending text from buffer directly.

Yes, lua/neovim is much better ;-)

Not sure if this is helpful or not, but wouldn't quoting the parameter of the command(s) help addressing special characters etc.? I always get uncomfortable when plugins use a syntax of `EXEC %run filename.py` and not `EXEC "%run filename.py"` -- especially in Windows, not using quotes can open so many rabbit holes, and here it looks like a similar case. 

Or would the quotes open up other kinds of rabbit holes?

**Comment by milanglacier** [comment]
Why do you want to quote?

The characters you type in cmdline are sent **literally** to the REPL. No escape is happening and I don't see any possibility why do we want to escape any characters in cmdline.

**Comment by gilbh** [comment]
Quotes would enable sending special characters, but since there is complete control over the REPL via the plugin, it might be totally fine to work with literals strings. If in the future, I find that quotes are needed for any reason, I'll get back to you.
