### ISSUE TITLE
Make a REPL a normal terminal buffer

### ISSUE THREAD

**Issue by leg7** [milanglacier/yarepl.nvim#27]
Hi, I would like to know how I can make the REPL started by yarepl to be a standard term buffer instead of one with a special name and ft. Here is an image of how I want the buffer to be named:

![image](https://github.com/user-attachments/assets/1a659944-34b9-4859-b3de-9378e096143a)

**Comment by milanglacier** [comment]
could you let me know the rationale behind why you want to do this?

Give REPLs created by plugin dedicated names are common practice. If you check toggleterm.nvim, they do the same thing.

**Comment by leg7** [comment]
I want to do this so that the repl session can be restored automatically by [auto-session](https://github.com/rmagatti/auto-session). If the repl buffer is just named `#ghci#` then auto-sessions won't know how to restore it properly.

I should have mentioned this from the start to avoid falling for the [XY problem](https://xyproblem.info/) but I didn't want to bring up unrelated plugins.

**Comment by milanglacier** [comment]
wow. That’s legitimate. I don’t know those session managers can even restore terminal buffers.

I’ll add an opt-out option to disable  rename of the buffer

**Comment by milanglacier** [comment]
You can try set the option `format_repl_buffers_names` to false.

**Comment by leg7** [comment]
Yeah that fixed it.

Thank you so much!

**Comment by leg7** [comment]
@milanglacier 
When I restore a session yarepl can't send commands to the REPL that was restored because it says "REPL doesn't exist". This happens when I try to close the repl or send input to it.

I've tried using `REPLAttachBufferToREPL` but I don't think it's meant to do what I think. (Registering a buffer as a REPL)

Is there a way to work around this issue?

**Comment by milanglacier** [comment]
This is because yarepl internally keeps tracking the REPL with `M._repls`. Since the terminal buffer is restored by your plugins, not opened by yarepl, so it cannot keep track those REPLs.

I don't know how does restore session work and I can't think there would be an elegant way to handle this. But of course the workaround exists.

Here is what you would do:

After your session get restored, you will need to find the appropriate  time (either via an autocmd or whatever with your session management plugin's API):

```lua
local yarepl = require('yarepl')

-- get the buffer number of your terminal buffer
-- get the terminal job id of your terminal buffer via vim.b.terminal_job_id
yarepl._repls = { [1] =  { bufnr = bufnr, term = term_job_id, name = 'your REPL meta name' } }
```

Note that this is an internal API and I might refactor the design in the future, but I don't have this plan right now.
